McFarlandProject1: McFarlandProject1.o
	gcc -o McFarlandProject1 McFarlandProject1.o
McFarlandProject1.o: McFarlandProject1.c McFarlandProject1.h
	gcc -c -g -Werror -Wall McFarlandProject1.c
clean:
	rm -f *.o
	rm -f McFarlandProject1
